export const CATEGORIES = [
  { name: 'Lebensmittel', icon: 'fast-food-outline' },
  { name: 'Einkäufe', icon: 'cart-outline' },
  { name: 'Restaurant/Bar', icon: 'wine-outline' },
  { name: 'Transport', icon: 'car-outline' },
  { name: 'Freizeit', icon: 'game-controller-outline' },
  { name: 'Wohnen', icon: 'home-outline' },
  { name: 'Rechnungen', icon: 'receipt-outline' },
  { name: 'Gesundheit', icon: 'heart-outline' },
  { name: 'Bildung', icon: 'school-outline' },
  { name: 'Arbeit', icon: 'briefcase-outline' },
  { name: 'Kleidung', icon: 'shirt-outline' },
  { name: 'Finanzen', icon: 'cash-outline' },
  { name: 'Reisen', icon: 'airplane-outline' },
  { name: 'Geschenke', icon: 'gift-outline' },
  { name: 'Haushalt', icon: 'hammer-outline' },
  { name: 'Ideen/Projekte', icon: 'bulb-outline' },
  { name: 'Musik/Events', icon: 'musical-notes-outline' },
  { name: 'Technik', icon: 'rocket-outline' },
  { name: 'Sonstiges', icon: 'ellipsis-horizontal-outline' },
];
